/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-TIFF.h
 #	source generated by 4D Plugin Wizard
 #	Project : TIFF
 #	author : miyako
 #	2024/12/20
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TIFF_H
#define PLUGIN_TIFF_H

#include "4DPluginAPI.h"
#include "tiffio.h"
#include <vector>
#include <map>
#include <string>

#pragma mark -

static void TIFF_Count_pages(PA_PluginParameters params);
static void TIFF_GET_PAGES(PA_PluginParameters params);
static void TIFF_Create_from_array(PA_PluginParameters params);

typedef struct
{
    uint8_t *ptr;
    PA_long32 len;
    PA_long32 pos;
} tiff_src;

typedef struct
{
    std::vector<uint8_t> *buf;
    PA_long32 pos;
} tiff_dst;

#endif /* PLUGIN_TIFF_H */
